name: Contexts
on: push
env:
  EXAPLE: "TOP"
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "EXAMPLE: $EXAMPLE"
      - env:
          EXAMPLE: "STEP LEVEL ENV"
        run: echo "EXAMPLE: $EXAMPLE"